# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15b7f4f0a93cc197d17bf7f4744a399e"
name = "Fast Cod Pro"
application_url = "https://app.fastcodpro.com"
embedded = true
handle = "fast-cod-pro"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://app.fastcodpro.com/webhooks/privacy"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_orders,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app.fastcodpro.com/auth/callback",
  "https://app.fastcodpro.com/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "/proxy"
prefix = "apps"
subpath = "fast-cod-pro"
